"""intitialized at heroku

Revision ID: 120cd68b486d
Revises: 702463a425e
Create Date: 2015-08-23 15:29:49.766858

"""

# revision identifiers, used by Alembic.
revision = '120cd68b486d'
down_revision = '702463a425e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
