"""completed bool on logs

Revision ID: 1455d9c95734
Revises: 1ecc5d85f815
Create Date: 2015-09-25 13:34:37.684253

"""

# revision identifiers, used by Alembic.
revision = '1455d9c95734'
down_revision = '1ecc5d85f815'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'administrators', 'schools', ['school_id'], ['id'])
    op.create_foreign_key(None, 'coaches', 'schools', ['school_id'], ['id'])
    op.add_column('logs', sa.Column('completed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_logs_completed'), 'logs', ['completed'], unique=False)
    op.create_foreign_key(None, 'teachers', 'schools', ['school_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teachers', type_='foreignkey')
    op.drop_index(op.f('ix_logs_completed'), table_name='logs')
    op.drop_column('logs', 'completed')
    op.drop_constraint(None, 'coaches', type_='foreignkey')
    op.drop_constraint(None, 'administrators', type_='foreignkey')
    ### end Alembic commands ###
