"""linked many coaches to many teachers

Revision ID: 1a0979e64941
Revises: 581f6865f02d
Create Date: 2015-09-06 10:59:52.125826

"""

# revision identifiers, used by Alembic.
revision = '1a0979e64941'
down_revision = '581f6865f02d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_teacher_link',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'coach_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coach_teacher_link')
    ### end Alembic commands ###
