"""added timestamp completed to logs

Revision ID: 1abfb1cdc0ea
Revises: 38c25da6e018
Create Date: 2015-10-10 08:56:25.842989

"""

# revision identifiers, used by Alembic.
revision = '1abfb1cdc0ea'
down_revision = '38c25da6e018'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('timestamp_completed', sa.DateTime(), nullable=True))
    op.add_column('logs', sa.Column('timestamp_created', sa.DateTime(), nullable=True))
    op.create_index('ix_logs_timestamp_created', 'logs', ['timestamp_created'], unique=False)
    op.drop_index('ix_logs_timestamp', 'logs')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_logs_timestamp', 'logs', ['timestamp'], unique=False)
    op.drop_index('ix_logs_timestamp_created', 'logs')
    op.drop_column('logs', 'timestamp_created')
    op.drop_column('logs', 'timestamp_completed')
    ### end Alembic commands ###
