"""typos

Revision ID: 1ecc5d85f815
Revises: 20c64950bba0
Create Date: 2015-09-08 16:37:25.092851

"""

# revision identifiers, used by Alembic.
revision = '1ecc5d85f815'
down_revision = '20c64950bba0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
