"""typo

Revision ID: 20c64950bba0
Revises: 296fda7f8e2b
Create Date: 2015-09-08 16:35:56.240270

"""

# revision identifiers, used by Alembic.
revision = '20c64950bba0'
down_revision = '296fda7f8e2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'coteach')
    op.drop_column('logs', 'email_help')
    op.drop_column('logs', 'contact_nit')
    op.drop_column('logs', 'unbelieavble')
    op.drop_column('logs', 'general_teacher_tech_help')
    op.drop_column('logs', 'jeffpd_publication')
    op.drop_column('logs', 'hardware')
    op.drop_column('logs', 'teacher_chromebook_help')
    op.drop_column('logs', 'coplan')
    op.drop_column('logs', 'google_resources')
    op.drop_column('logs', 'google_maintenance')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('google_maintenance', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('google_resources', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('coplan', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('teacher_chromebook_help', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('hardware', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('jeffpd_publication', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('general_teacher_tech_help', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('unbelieavble', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('contact_nit', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('email_help', sa.BOOLEAN(), nullable=True))
    op.add_column('logs', sa.Column('coteach', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###
