"""teachers, coaches, logs

Revision ID: 21e4babf04ee
Revises: 4af9b0afa258
Create Date: 2015-08-28 15:31:41.653669

"""

# revision identifiers, used by Alembic.
revision = '21e4babf04ee'
down_revision = '4af9b0afa258'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
