"""made tags table

Revision ID: 296fda7f8e2b
Revises: 5419159ac0cb
Create Date: 2015-09-08 16:28:54.601841

"""

# revision identifiers, used by Alembic.
revision = '296fda7f8e2b'
down_revision = '5419159ac0cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('log_tag_link',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'log_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_tag_link')
    op.drop_table('tags')
    ### end Alembic commands ###
