"""added tags to logs

Revision ID: 3154c750f093
Revises: 337c8696cf2a
Create Date: 2015-09-07 13:57:53.932576

"""

# revision identifiers, used by Alembic.
revision = '3154c750f093'
down_revision = '337c8696cf2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('contact_nit', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('coplan', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('coteach', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('general_teacher_tech_help', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('google_maintenance', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('google_resources', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('hardware', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('jeffpd_publication', sa.Boolean(), nullable=True))
    op.add_column('logs', sa.Column('teacher_chromebook_help', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'teacher_chromebook_help')
    op.drop_column('logs', 'jeffpd_publication')
    op.drop_column('logs', 'hardware')
    op.drop_column('logs', 'google_resources')
    op.drop_column('logs', 'google_maintenance')
    op.drop_column('logs', 'general_teacher_tech_help')
    op.drop_column('logs', 'coteach')
    op.drop_column('logs', 'coplan')
    op.drop_column('logs', 'contact_nit')
    ### end Alembic commands ###
