"""added next to log

Revision ID: 337c8696cf2a
Revises: 18b4980d0b2
Create Date: 2015-09-07 13:48:51.068038

"""

# revision identifiers, used by Alembic.
revision = '337c8696cf2a'
down_revision = '18b4980d0b2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
