"""added email to log tags

Revision ID: 349ab12c64ed
Revises: 5a376c421d70
Create Date: 2015-09-08 11:52:23.457779

"""

# revision identifiers, used by Alembic.
revision = '349ab12c64ed'
down_revision = '5a376c421d70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('email_help', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'email_help')
    ### end Alembic commands ###
