"""added time to logs

Revision ID: 38c25da6e018
Revises: 1455d9c95734
Create Date: 2015-10-06 09:20:28.624178

"""

# revision identifiers, used by Alembic.
revision = '38c25da6e018'
down_revision = '1455d9c95734'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('time', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'time')
    ### end Alembic commands ###
