"""added admin role

Revision ID: 40ec65d9b0b3
Revises: 349ab12c64ed
Create Date: 2015-09-08 12:25:24.417617

"""

# revision identifiers, used by Alembic.
revision = '40ec65d9b0b3'
down_revision = '349ab12c64ed'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('administrators')
    ### end Alembic commands ###
