"""teachers, coaches, logs

Revision ID: 4af9b0afa258
Revises: a28030345ff
Create Date: 2015-08-28 15:07:36.266977

"""

# revision identifiers, used by Alembic.
revision = '4af9b0afa258'
down_revision = 'a28030345ff'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
