"""added admin to school

Revision ID: 5419159ac0cb
Revises: 5a7ad54d9297
Create Date: 2015-09-08 15:07:57.899250

"""

# revision identifiers, used by Alembic.
revision = '5419159ac0cb'
down_revision = '5a7ad54d9297'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrators', sa.Column('school_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('administrators', 'school_id')
    ### end Alembic commands ###
