"""added type to coach

Revision ID: 55bd2e159b91
Revises: 1abfb1cdc0ea
Create Date: 2015-10-10 11:52:37.381983

"""

# revision identifiers, used by Alembic.
revision = '55bd2e159b91'
down_revision = '1abfb1cdc0ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('coach_type', sa.String(length=64), nullable=True))
    op.create_index('ix_logs_timestamp', 'logs', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_timestamp', 'logs')
    op.drop_column('coaches', 'coach_type')
    ### end Alembic commands ###
