"""teachers, coaches, logs

Revision ID: 581f6865f02d
Revises: 21e4babf04ee
Create Date: 2015-08-28 15:34:36.751200

"""

# revision identifiers, used by Alembic.
revision = '581f6865f02d'
down_revision = '21e4babf04ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
