"""added unbelievable to tags

Revision ID: 5a376c421d70
Revises: 3154c750f093
Create Date: 2015-09-07 21:30:15.304036

"""

# revision identifiers, used by Alembic.
revision = '5a376c421d70'
down_revision = '3154c750f093'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('unbelieavble', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'unbelieavble')
    ### end Alembic commands ###
