"""added school class to db

Revision ID: 5a7ad54d9297
Revises: 40ec65d9b0b3
Create Date: 2015-09-08 14:39:38.868710

"""

# revision identifiers, used by Alembic.
revision = '5a7ad54d9297'
down_revision = '40ec65d9b0b3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'coaches', sa.Column('school_id', sa.Integer(), nullable=True))
    op.add_column(u'teachers', sa.Column('school_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'teachers', 'school_id')
    op.drop_column(u'coaches', 'school_id')
    op.drop_table('schools')
    ### end Alembic commands ###
