"""teachers, coaches, logs

Revision ID: a28030345ff
Revises: 3464c79fa2a6
Create Date: 2015-08-28 14:55:18.758542

"""

# revision identifiers, used by Alembic.
revision = 'a28030345ff'
down_revision = '3464c79fa2a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('coach_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_table('log_teacher_link',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('log_id', 'teacher_id')
    )
    op.drop_table('posts')
    op.add_column(u'users', sa.Column('type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'users', 'type')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coach_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], [u'users.id'], name=u'posts_coach_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], [u'users.id'], name=u'posts_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'posts_pkey')
    )
    op.drop_table('log_teacher_link')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('teachers')
    op.drop_table('coaches')
    ### end Alembic commands ###
